- name: No sys.path changes
  pattern: "sys\\.path\\.append|sys\\.path\\.insert"
  filePattern: src/.*\.py

- name: IPython debug leftover
  pattern: "IPython\\.embed()"
  filePattern: .*\.py

- name: Use relative imports
  pattern: "import pytest_recording|from pytest_recording"
  filePattern: src/.*\.py
